# Generated by Django 6.0.6 on 2026-06-05 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'media_links',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='media_links_entity__1e2e97_idx')],
            },
        ),
    ]
