# Generated by Django 6.0.6 on 2026-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_medialink'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medialink',
            constraint=models.UniqueConstraint(fields=('media_file', 'entity_type', 'entity_id'), name='unique_media_link'),
        ),
    ]
