# Generated by Django 6.0.6 on 2026-08-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_medialink_unique_media_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='type',
        ),
    ]
